### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by MancaStrgar** [MancaStrgar/APPR-2017-18#5]
Ko kliknem pull je nekaj narobe:
>>> C:/Program Files/Git/bin/git.exe pull
error: cannot lock ref 'refs/remotes/origin/master': unable to resolve reference 'refs/remotes/origin/master': reference broken
From https://github.com/MancaStrgar/APPR-2017-18
 ! [new branch]      master     -> origin/master  (unable to update local ref)

Kaj moram narediti, da bo ok?

**Comment by jaanos** [comment]
Nekaj je očitno šlo narobe pri zadnjem commitu ali pullu. Verjetno bo najlažje, če na novo kloniraš repozitorij (v RStudiu izberi *New project...* in potem uporabi drugo mapo kot sicer); če imaš pri sebi še kakšne spremembe, ki jih na GitHubu še ni (ne glede na to ali si jih že vključila v commit ali ne), pa skopiraj datoteke iz starega projekta v novega in potem vse spremembe vključi v commit.
